# Generated by Django 5.2.1 on 2025-05-29 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_book_book_notes_book_genre_book_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='book',
            name='publication_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='shelved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='book',
            name='toBeRead',
            field=models.BooleanField(default=False),
        ),
    ]
