# Generated by Django 5.2.1 on 2025-05-30 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_book_isbn_book_language_book_page_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='content_warnings',
            field=models.TextField(blank=True, null=True),
        ),
    ]
