# Generated by Django 5.2.1 on 2025-05-30 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_book_cover_book_cover_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='cover_url',
        ),
    ]
