# Generated by Django 5.2.1 on 2025-05-30 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0009_remove_book_cover_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='emoji',
            field=models.CharField(blank=True, default='📚', max_length=10, null=True),
        ),
    ]
