# Generated by Django 5.2.1 on 2025-05-30 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0013_alter_genre_options_genre_name_remove_book_genre_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['-created_at'], 'verbose_name': 'Book', 'verbose_name_plural': 'Books'},
        ),
        migrations.AlterModelOptions(
            name='genre',
            options={'ordering': ['name'], 'verbose_name': 'Genre', 'verbose_name_plural': 'Genres'},
        ),
        migrations.RemoveField(
            model_name='genre',
            name='id',
        ),
        migrations.AddField(
            model_name='book',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='covers/'),
        ),
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.CharField(blank=True, choices=[('fiction', 'Fiction'), ('non-fiction', 'Non-Fiction'), ('sci-fi', 'Science Fiction'), ('fantasy', 'Fantasy'), ('mystery', 'Mystery'), ('biography', 'Biography'), ('history', 'History'), ('romance', 'Romance'), ('thriller', 'Thriller'), ('horror', 'Horror'), ('young-adult', 'Young Adult'), ('children', 'Children'), ('dystopian', 'Dystopian'), ('utopian', 'Utopian'), ('supernatural', 'Supernatural'), ('paranormal', 'Paranormal'), ('graphic-novel', 'Graphic Novel'), ('poetry', 'Poetry'), ('drama', 'Drama'), ('classic', 'Classic'), ('unknown', 'Unknown')], default='unknown', max_length=50),
        ),
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
        migrations.AlterField(
            model_name='genre',
            name='code',
            field=models.CharField(choices=[('fiction', 'Fiction'), ('non-fiction', 'Non-Fiction'), ('sci-fi', 'Science Fiction'), ('fantasy', 'Fantasy'), ('mystery', 'Mystery'), ('biography', 'Biography'), ('history', 'History'), ('romance', 'Romance'), ('thriller', 'Thriller'), ('horror', 'Horror'), ('young-adult', 'Young Adult'), ('children', 'Children'), ('dystopian', 'Dystopian'), ('utopian', 'Utopian'), ('supernatural', 'Supernatural'), ('paranormal', 'Paranormal'), ('graphic-novel', 'Graphic Novel'), ('poetry', 'Poetry'), ('drama', 'Drama'), ('classic', 'Classic'), ('unknown', 'Unknown')], max_length=50, primary_key=True, serialize=False),
        ),
    ]
