# Generated by Django 5.2.1 on 2025-05-30 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0014_alter_book_options_alter_genre_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='cover',
        ),
        migrations.RemoveField(
            model_name='book',
            name='publication_date',
        ),
        migrations.AddField(
            model_name='book',
            name='currently_reading',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='book',
            name='did_not_finish',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='book',
            name='favorite',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='book',
            name='recommended_to_me',
            field=models.BooleanField(default=False),
        ),
    ]
