# Generated by Django 5.2.1 on 2025-05-30 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0015_remove_book_cover_remove_book_publication_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='additional_genres',
            field=models.TextField(blank=True, help_text='Comma-separated list of additional genres beyond the primary genre', null=True),
        ),
    ]
