# Generated by Django 5.2.1 on 2025-05-30 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0017_book_publication_date_bookphoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='number_of_chapters',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
